### ISSUE TITLE
"Illegal Instruction(core dumped)" when trying to initialise a Playback object

### ISSUE THREAD

**Issue by DilettanteProjects** [cheofusi/just_playback#42]
On my phone in termux, everything works like a charm, but on my thinkpad I get the above mentioned error.
A cursory google search seems to imply this is because of incompatibility with older processors, but I'm a bit out of my depth on this.

**Comment by cheofusi** [comment]
Hi @DilettanteProjects,

What processor powers your ThinkPad?

**Comment by DilettanteProjects** [comment]
> What processor powers your ThinkPad?

An Intel i5-2520M.

**Comment by cheofusi** [comment]
Seems like the Github Action's Linux runner produces wheels containing instructions that are only supported by later intel processors.

You can build just-playback yourself using

` pip install --no-binary just_playback just_playback`

**Comment by DilettanteProjects** [comment]
Thanks a bunch, works perfectly now!

**Comment by domdfcoding** [comment]
Can you compile with AVX2 instructions disabled (as it was `vinserti128` for me that was causing the illegal instruction)? That would be targeting x86-64-v2 rather than x86-64-v3. Or gate it behind a check for CPU support, which it looks like numpy does and I thought the compiler would do automatically, but maybe not for AVX2.
